In [1]:
import tensorflow as tf
print (tf.__version__)
import numpy as np
tensor_1d=np.array([1.3, 1, 4.0, 23.99])
print (tensor_1d[2])
print (tensor_1d)

2.6.0
4.0
[ 1.3   1.    4.   23.99]


In [2]:
import numpy as np
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)
print(tensor_2d[3][3])


[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
15


In [16]:
import tensorflow as tf
import numpy as np
mat1 = np.array([(2,2,2),(3,3,3),(2,2,2)],dtype=int)
mat2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype=int)
print(mat1)
print(mat2)
mat1=tf.constant(mat1)
mat2=tf.constant(mat2)
mat_mul=tf.matmul(mat1,mat2)
mat_add=tf.add(mat1,mat2)
mat3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype=float)
print (mat3)
mat_det=tf.linalg.det(mat3)
with tf.compat.v1.Session() as sess:
    res1=sess.run(mat_mul)
    res2=sess.run(mat_add)
    res3=sess.run(mat_det)
print(res1)
print(res2)
print(res3)

[[2 2 2]
 [3 3 3]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
[[6 6 6]
 [9 9 9]
 [6 6 6]]
[[3 3 3]
 [4 4 4]
 [3 3 3]]
55.99999999999997


# OR

In [15]:
import tensorflow as tf
import numpy as np
mat1 = np.array([(2,2,2),(3,3,3),(2,2,2)],dtype=int)
mat2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype=int)
print(mat1)
print(mat2)
#mat1=tf.constant(mat1)
#mat2=tf.constant(mat2)
mat_mul=tf.matmul(mat1,mat2)
mat_add=tf.add(mat1,mat2)
mat3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype=float)
print (mat3)
mat_det=tf.linalg.det(mat3)
#tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session() 
res1=sess.run(mat_mul)
res2=sess.run(mat_add)
res3=sess.run(mat_det)
print(res1)
print(res2)
print(res3)

[[2 2 2]
 [3 3 3]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
[[6 6 6]
 [9 9 9]
 [6 6 6]]
[[3 3 3]
 [4 4 4]
 [3 3 3]]
55.99999999999997


# OR

In [30]:
#import tensorflow as tf
import numpy as np
import tensorflow._api.v2.compat.v1 as tf
tf.disable_v2_behavior()
matrix1 = np.array([(2,2,2),(3,3,3),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

print (matrix1)
print (matrix2)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print (matrix_3)

matrix_det = tf.matrix_determinant(matrix_3)
with tf.Session() as sess:
   result1 = sess.run(matrix_product)
   result2 = sess.run(matrix_sum)
   result3 = sess.run(matrix_det)

print (result1)
print (result2)
print (result3)

[[2 2 2]
 [3 3 3]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
[[6 6 6]
 [9 9 9]
 [6 6 6]]
[[3 3 3]
 [4 4 4]
 [3 3 3]]
55.999992


In [13]:
x = tf.constant(35, name='x')
y = tf.Variable(x + 5, name='y')

model = tf.global_variables_initializer() 

with tf.Session() as session:
    session.run(model)
    print(session.run(y))

40


In [14]:
x = tf.Variable(35, name='x')
y = tf.Variable(x + 5, name='y')

model = tf.global_variables_initializer() 

with tf.Session() as session:
    session.run(model)
    print(session.run(y))

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
40


In [28]:
import tensorflow as tf
T,F=1.,-1.
B=1.
train_in=[
         [T,T,B],
         [T,F,B],
         [F,T,B],
         [F,F,B]
            ]
train_out=[
            [T],
            [F],
            [F],
            [F]
            ]
w=tf.Variable(tf.random.normal([3,1]))
print(w)


<tf.Variable 'Variable_6:0' shape=(3, 1) dtype=float32>


In [4]:
import tensorflow as tf
print("No. GPU available:", len(tf.config.experimental.list_physical_devices('GPU')))

No. GPU available: 0


In [7]:
from tensorflow import keras

In [11]:
print(tf.__version__)


2.6.0
